# Generated by Django 5.1 on 2024-09-02 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=45, verbose_name='Nome do Equipamento')),
                ('peso_equipamento', models.FloatField(verbose_name='Peso do Equipamento')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome do Usuario')),
                ('sobrenome', models.CharField(max_length=45, verbose_name='Sobrenome do Usuario')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('senha', models.CharField(max_length=45, verbose_name='Senha')),
                ('imagem_perfil', models.CharField(max_length=1000, verbose_name='Link da Imagem')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticoes', models.IntegerField(verbose_name='Repeticoes')),
                ('peso_exercicio', models.FloatField(verbose_name='Peso do Exercicio')),
                ('series', models.IntegerField(verbose_name='Series')),
                ('descanso', models.IntegerField(verbose_name='Descanso')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Exercicio',
                'verbose_name_plural': 'Exercicios',
            },
        ),
        migrations.CreateModel(
            name='FichaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ficha_treino', models.CharField(max_length=45, verbose_name='Nome da Ficha de Treino')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercicio', verbose_name='Exercicio')),
            ],
            options={
                'verbose_name': 'Ficha de Treino',
                'verbose_name_plural': 'Fichas de Treino',
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_treino', models.DateField(verbose_name='Data do Treino')),
                ('duracao', models.IntegerField(verbose_name='Duracao')),
                ('nome_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fichatreino', verbose_name='Nome do Treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('data_comentario', models.DateField(verbose_name='Data do Comentario')),
                ('nome_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuario')),
            ],
            options={
                'verbose_name': 'Interacao',
                'verbose_name_plural': 'Interacoes',
            },
        ),
    ]
