# Generated by Django 5.1.1 on 2024-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='nome_exercicio',
            field=models.CharField(default=1, max_length=45, verbose_name='Nome do exercicio'),
            preserve_default=False,
        ),
    ]
