# Generated by Django 5.1.1 on 2024-09-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exercicio_nome_exercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatreino',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fichatreino', verbose_name='Ficha Treino'),
            preserve_default=False,
        ),
    ]
