# Generated by Django 5.1.1 on 2024-10-01 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fichatreino_nome_ficha_treino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='ficha_treino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fichatreino', verbose_name='Ficha de Treino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacao',
            name='nota',
            field=models.IntegerField(default=0, verbose_name='Nota'),
        ),
    ]
