# Generated by Django 5.1.1 on 2024-10-17 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_interacao_ficha_treino_interacao_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treino', models.CharField(max_length=255)),
                ('data_treino', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso_exercicio', models.FloatField(blank=True, null=True)),
                ('repeticoes', models.IntegerField(blank=True, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('descanso', models.IntegerField(blank=True, null=True)),
                ('treino_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
