# Generated by Django 5.1.1 on 2024-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuariotreino',
            name='nome_exercicio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
