# Generated by Django 5.1.1 on 2024-10-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_usuario_user_usuariotreino_nome_exercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariotreino',
            name='nome_exercicio',
        ),
    ]
