# Generated by Django 5.1.1 on 2024-10-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_usuariotreino_nome_exercicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioTreino',
        ),
    ]
